# Generated by Django 6.0.1 on 2026-01-09 16:06
# pylint: disable=invalid-name,missing-module-docstring
"""Migration altering Chat unique constraints and chat_id field."""
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    """Migration altering Chat unique constraints and chat_id field."""

    dependencies = [
        ('chat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chat',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='chat',
            name='chat_id',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='chat',
            unique_together={('chat_id', 'user')},
        ),
    ]
