# Generated by Django 6.0.1 on 2026-01-09 16:06
# pylint: disable=invalid-name,missing-module-docstring
"""Migration altering Chat chat_id field."""
from django.db import migrations, models


class Migration(migrations.Migration):
    """Migration altering Chat chat_id field."""

    dependencies = [
        ('chat', '0002_alter_chat_unique_together_alter_chat_chat_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='chat_id',
            field=models.CharField(max_length=100),
        ),
    ]
