# Generated by Django 6.0.1 on 2026-01-09 16:45
# pylint: disable=invalid-name,missing-module-docstring
"""Migration creating Document model."""
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def document_upload_path(instance, filename):
    """Generate upload path for documents"""
    return f'documents/{instance.user.id}/{filename}'


class Migration(migrations.Migration):
    """Migration creating Document model."""

    dependencies = [
        ('chat', '0003_alter_chat_chat_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True, primary_key=True,
                    serialize=False, verbose_name='ID'
                )),
                ('file', models.FileField(upload_to=document_upload_path)),
                ('filename', models.CharField(max_length=255)),
                ('file_type', models.CharField(max_length=50)),
                ('file_size', models.BigIntegerField()),
                ('extracted_text', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='documents', to=settings.AUTH_USER_MODEL
                )),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
