# Generated by Django 4.2.7 on 2026-01-10 15:39
# pylint: disable=invalid-name,missing-module-docstring
"""Migration altering id fields for Chat, ChatMessage, and Document."""
from django.db import migrations, models


class Migration(migrations.Migration):
    """Migration altering id fields for Chat, ChatMessage, and Document."""

    dependencies = [
        ('chat', '0005_chat_conversation_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='id',
            field=models.AutoField(
                auto_created=True, primary_key=True,
                serialize=False, verbose_name='ID'
            ),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='id',
            field=models.AutoField(
                auto_created=True, primary_key=True,
                serialize=False, verbose_name='ID'
            ),
        ),
        migrations.AlterField(
            model_name='document',
            name='id',
            field=models.AutoField(
                auto_created=True, primary_key=True,
                serialize=False, verbose_name='ID'
            ),
        ),
    ]
