# Generated by Django 6.0.1 on 2026-01-10 15:48
# pylint: disable=invalid-name,missing-module-docstring
"""Migration altering id fields and session_id for Chat models."""
from django.db import migrations, models


class Migration(migrations.Migration):
    """Migration altering id fields and session_id for Chat models."""

    dependencies = [
        ('chat', '0007_chat_session_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='id',
            field=models.BigAutoField(
                auto_created=True, primary_key=True,
                serialize=False, verbose_name='ID'
            ),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='id',
            field=models.BigAutoField(
                auto_created=True, primary_key=True,
                serialize=False, verbose_name='ID'
            ),
        ),
        migrations.AlterField(
            model_name='document',
            name='id',
            field=models.BigAutoField(
                auto_created=True, primary_key=True,
                serialize=False, verbose_name='ID'
            ),
        ),
        migrations.AlterField(
            model_name='chat',
            name='session_id',
            field=models.PositiveIntegerField(
                help_text=(
                    'Global session ID starting from 1, '
                    'sequential across all users'
                ),
                unique=True
            ),
        ),
        migrations.AlterUniqueTogether(
            name='chat',
            unique_together={('chat_id', 'user')},
        ),
    ]
