# Generated by Django 4.2.7 on 2026-01-10 16:10
# pylint: disable=invalid-name,missing-module-docstring
"""Migration removing file field from Document model."""
from django.db import migrations


class Migration(migrations.Migration):
    """Migration removing file field from Document model."""

    dependencies = [
        ('chat', '0010_make_session_id_unique'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='file',
        ),
    ]
